// scripts/syncPlayers.ts
//
// Sincroniza una lista de jugadores concreta, escrita a mano.
// Ejecutar con: npx tsx scripts/syncPlayers.ts

import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { syncJugadorDesdeWikipedia } from "../src/lib/wikipediaSync";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

const JUGADORES_INICIALES = [
  "Joan García",
  "Wojciech Szczęsny",
  "Marc ter Stegen",
  "Ronald Araújo",
  "Alejandro Balde",
  "Andreas Christensen",
  "Pau Cubarsí Paredes",
  "Xavi Espart",
  "Eric García",
  "Jules Koundé",
  "Gerard Martín",
  "Jofre Torrents",
  "Marc Bernal",
  "Marc Casadó",
  "Fermín",
  "Gavi",
  "Tomás Marqués",
  "Dani Olmo",
  "Pedri",
  "Frenkie de Jong",
  "Hamza Abdelkarim",
  "Roony Bardghji",
  "Anthony Gordon",
  "Lamine Yamal",
  "Raphinha",
  "Ferran Torres",
  "Juan Musso",
  "Jan Oblak",
  "José María Giménez",
  "Álex Grimaldo",
  "Hancko",
  "Robin Le Normand",
  "Marcos Llorente",
  "Nahuel Molina",
  "Marc Pubill",
  "Ruggeri",
  "Pablo Barrios",
  "Jhonny Cardoso",
  "Hjulmand",
  "Koke",
  "Rodrigo Mendoza",
  "Thiago Almada",
  "Julián Álvarez",
  "Álex Baena",
  "Marcos Llorente",
  "Ademola Lookman",
  "Giuliano Simeone",
  "Sørloth",
  "Unai Simón",
  "Yeray",
  "Jesús Areso",
  "Yuri",
  "Gorosabel",
  "Aymeric Laporte",
  "Aitor Paredes",
  "Dani Vivian",
  "Mikel Jauregizar",
  "Robert Navarro",
  "Beñat Prados",
  "Ruíz de Galarreta",
  "Oihan Sancet",
  "Mikel Vesga",
  "Álex Berenguer",
  "Álvaro Djaló",
  "Gorka Guruzeta",
  "Maroan Sannadi",
  "Nico Serrano",
  "Iñaki Williams",
  "Nico Williams",
  "Stole Dimitrievski",
  "Copete",
  "Foulquier",
  "José Gayà",
  "César Tárrega",
  "Jesús Vázquez",
  "André Almeida",
  "Javi Guerra",
  "Pepelu",
  "Guido Rodríguez",
  "A. Danjuma",
  "Hugo Duro",
  "Dani Raba",
  "Luis Rioja",
  "Umar Sadiq",
  "Diego Conde",
  "Luíz Júnior",
  "Arnau Tenas",
  "Sergi Cardona",
  "Logan Costa",
  "Willy Kambwala Ndengushi",
  "Mouriño",
  "Pau Navarro",
  "Renato Veiga",
  "Buchanan",
  "Santi Comesaña",
  "Pape Gueye",
  "Alberto Moleiro",
  "Hugo López",
  "Mikautadze",
  "Gerard Moreno",
  "Oluwaseyi",
  "Nicolas Pépé",
  "Ayoze Pérez",
  "Loiodice",
  "Kirian Rodríguez",
  "Jesé",
  "Sandro Ramírez",
  "O. Vlachodimos",
  "José Ángel Carmona",
  "T. Nianzou",
  "Adrià Pedrosa",
  "Kike Salas",
  "Juanlu Sánchez",
  "L. Agoumé",
  "Jon Guridi",
  "Juan Iglesias",
  "Joan Jordán",
  "Djibril Sow",
  "Rubén Vargas",
  "Akor Adams",
  "Ejuke",
  "Peque Fernández",
  "Isaac Romero",
  "Ignasi Miquel",
  "Rubén Peña",
  "Rubén Pulido",
  "Carlos Guirao",
  "Javi Hernández",
  "Roberto López",
  "Nico Lozano",
  "Melero",
  "Dani Rodríguez",
  "Andrés Campos",
  "Juan Cruz",
  "Marcos Alonso",
  "Sergio Carreira",
  "Javi Galán",
  "Álvaro Núñez",
  "Unai Núñez",
  "Javi Rodríguez",
  "Manu Sánchez",
  "Starfelt",
  "Aleix Febas",
  "Ilaix Moriba",
  "Hugo Sotelo",
  "M. Vecino",
  "Hugo Álvarez",
  "Iago Aspas",
  "Pablo Durán",
  "Borja Iglesias",
  "Ferran Jutglà",
  "W. Swedberg",
  "M. Dmitrović",
  "Leandro Cabrera",
  "Omar El Hilali",
  "Riedel",
  "Miguel Rubio",
  "Rubén Sánchez",
  "Edu Expósito",
  "Urko González",
  "Pol Lozano",
  "TDolan",
  "Roberto Fernández",
  "Kike García",
  "Jofre Carreras",
  "Pere Milla",
  "Antoniu Roca",
  "Thibaut Courtois",
  "Andriy Lunin",
  "Trent Alexander-Arnold",
  "Raúl Asencio",
  "Álvaro Fernández",
  "Marc Cucurella",
  "DDumfries",
  "Éder Militão",
  "Dean Huijsen",
  "Ibrahima Konaté",
  "Ferland Mendy",
  "Antonio Rüdiger",
  "Jude Bellingham",
  "Eduardo Camavinga",
  "Brahim Díaz",
  "Arda Güler",
  "Thiago Pitarch",
  "Bernardo Silva",
  "Aurelien Tchouaméni",
  "Federico Valverde",
  "Gonzalo García",
  "Franco Mastantuono",
  "Kylian Mbappé",
  "Rodrygo",
  "Vinícius Júnior",
  "Antonio Sivera",
  "Jonny",
  "Nacho Tenaglia",
  "Yusi",
  "Carles Aleñá",
  "Antonio Blanco",
  "Guevara",
  "Pablo Ibáñez",
  "C. Benavídez",
  "Mikel Rodríguez",
  "Denis Suárez",
  "L. Boyé",
  "Mariano Díaz",
  "A. Manas",
  "Toni Martínez",
  "Angel Pérez",
  "A. Rebbach",
  "Álvaro Vallés",
  "Marc Bartra",
  "Héctor Bellerín",
  "Pablo Busto",
  "Junior Firpo",
  "Fran García",
  "Diego Llorente",
  "Natan",
  "Ángel Ortiz",
  "Ivan Corralejo",
  "Deossa",
  "Álvaro Fidalgo",
  "Pablo Fornals",
  "Isco",
  "Giovanni Lo Celso",
  "Marc Roca",
  "Antony",
  "A. Ezzalzouli",
  "Pablo García",
  "Cucho Hernández",
  "Iker Losada",
  "R. Marina",
  "Rodrigo Riquelme",
  "Aitor Ruibal",
  "Jorge Benito",
  "David Soria",
  "A. Abqar",
  "Davinchi",
  "Djené Dakonam",
  "Andrés García",
  "Kiko Femenía",
  "Javi Muñoz",
  "Mario Martín",
  "Adrián Riquelme",
  "Ramón Terrats",
  "Álex Sancris",
  "Joselu",
  "Juanmi",
  "Borja Mayoral",
  "M. Satriano",
  "Paulo Gazzaniga",
  "Alejandro Francés",
  "Gibert Jordana",
  "David López",
  "Arnau Martínez",
  "Álex Moreno",
  "Ricard Artero",
  "Fran Beltrán",
  "L. Kourouma",
  "Iván Martín",
  "A. Ounahi",
  "Joel Roca",
  "V. Tsygankov",
  "Donny van de Beek",
  "Bryan Gil",
  "Oleksandr Pishchur",
  "Abel Ruiz",
  "C. Stuani",
  "V. Vanat",
  "Álex Remiro",
  "J. Aramburu",
  "Sergio Gómez",
  "Jon Martín",
  "Aihen Muñoz",
  "Odriozola",
  "Zubeldia",
  "Ibai Aguirre",
  "Jon Gorrotxategi",
  "Y. Herrera",
  "Pablo Marín",
  "Carlos Soler",
  "L. Sučić",
  "Beñat Turrientes",
  "A. Zakharyan",
  "Barrenetxea",
  "Gonçalo Guedes",
  "T. Kubo",
  "O. Óskarsson",
  "Mikel Oyarzabal",
  "Iván Alejo",
  "Juanmi Latasa",
  "Marcos André",
  "A. Ndiaye",
  "Aitor Fernández",
  "Sergio Herrera",
  "V. Rosier",
  "Moncayola",
  "Iker Muñoz",
  "Aimar Oroz",
  "A. Budimir",
  "Raúl García",
  "Rubén García",
  "Moi Gómez",
  "Raul Moro",
  "A. Batalla",
  "Pep Chavarría",
  "F. Lejeune",
  "A. Rațiu",
  "R. Nteka",
  "Óscar Valentín",
  "Alemão",
  "Sergio Camello",
  "Isi Palazón",
  "Fran Pérez",
  "Jorge de Frutos",
  "Toni Lato",
  "J. Mojica",
  "Mateu Morey",
  "Raíllo",
  "Leo Sánchez",
  "M. Valjent",
  "Darder",
  "J. Garcia",
  "Manu Morlanes",
  "Arnau Puigmal",
  "Samú Costa",
  "Antonio Sánchez",
  "Pablo Torre",
  "J. Kalumba",
  "Abdón Prats",
  "Jan Virgili"
];


async function main() {
  for (const nombre of JUGADORES_INICIALES) {
    console.log(`\n→ Sincronizando ${nombre}...`);
    const resultado = await syncJugadorDesdeWikipedia(prisma, nombre);
    if (resultado.ok) {
      const aviso = resultado.renombrado ? `  (encontrado como "${resultado.nombreUsado}", revisa que sea correcto)` : "";
      console.log(
        `  ✓ ${resultado.etapas} etapas guardadas (${resultado.goles} goles, ${resultado.partidos} partidos totales)${aviso}`
      );
    } else {
      console.warn(`  ✗ Fallo: ${resultado.motivo}`);
    }
    await new Promise((r) => setTimeout(r, 1200));
  }
  await prisma.$disconnect();
  console.log("\nSync completo.");
}
 
main().catch((e) => {
  console.error(e);
  process.exit(1);
});