// scripts/syncPlayers.ts
//
// Sincroniza una lista de jugadores concreta, escrita a mano.
// Ejecutar con: npx tsx scripts/syncPlayers.ts
//
// Cada entrada de JUGADORES_INICIALES puede ser:
//   - un string con el nombre  -> búsqueda automática con las 4 estrategias
//   - un objeto { nombre, url } -> va directo a esa URL de Wikipedia,
//     sin búsqueda. Usar cuando el nombre no se detecta automáticamente.
//     La URL debe ser de en.wikipedia.org (ver aviso en wikipediaSync.ts).

import "dotenv/config";
import { writeFile } from "node:fs/promises";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { syncJugadorDesdeWikipedia } from "../src/lib/wikipediaSync";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

type EntradaJugador = string | { nombre: string; url: string };

const JUGADORES_INICIALES: EntradaJugador[] = [
  "Alessio Furlanetto",
  "Giacomo Giacomone",
  "Christos Mandas",
  "Edoardo Motta",
  "Nicolo Pannozzo",
  "Danilho Doekhi",
  "Romano Floriani Mussolini",
  "Samuel Gigot",
  "Adam Marušić",
  "Patricio Gabarrón",
  "Alfonso Pedraza",
  "Lorenzo Pellegrini",
  "Oliver Provstgaard",
  "Alessio Romagnoli",
  "Nuno Tavares",
  "Reda Belahyane",
  "Danilo Cataldi",
  "Fisayo Dele-Bashiru",
  "Valerio Farcomeni",
  "Manuel Lazzari",
  "Nicolò Rovella",
  "Kenneth Taylor",
  "Mattia Zaccagni",
  "Matteo Cancellieri",
  "Boulaye Dia",
  "Gustav Isaksen",
  "Tijjani Noslin",
  "Adrian Przyborek",
  "Petar Ratkov",
  "Mike Maignan",
  "Matteo Pittarella",
  "Pietro Terracciano",
  "Lorenzo Torriani",
  "Zachary Athekame",
  "Davide Bartesaghi",
  "Koni De Winter",
  "Pervis Estupiñán",
  "Matteo Gabbia",
  "Mario Gila",
  "David Odogu",
  "Strahinja Pavlović",
  "Fikayo Tomori",
  "Valentin Vladimirov",
  "Youssouf Fofana",
  "Ardon Jashari",
  "Ruben Loftus-Cheek",
  "Adrien Rabiot",
  "Samuele Ricci",
  "Alexis Saelemaekers",
  "Jacopo Sardo",
  "Filippo Terracciano",
  "Marco Valletta",
  "Santiago Giménez",
  "Filip Kostić",
  "Rafael Leão",
  "Christopher Nkunku",
  "Christian Pulišić",
  "Gonçalo Ramos",
  "Elia Caprile",
  "Giuseppe Ciocci",
  "Alen Sherri",
  "Andrea Cogoni",
  "Riyad Idrissi",
  "Yerry Mina",
  "Adam Obert",
  "Zé Pedro",
  "Nicola Pintus",
  "James Rodríguez",
  "Gabriele Zappa",
  "Michel Adopo",
  "Ayodele Akarakiri",
  "Agustín Albarracín",
  "Nicolò Cavuoti",
  "Alessandro Deiola",
  "Jacopo Fazzini",
  "Mattia Felici",
  "Nicola Grandu",
  "Jhon Liteta",
  "Romeo Malfitano",
  "Matteo Prati",
  "Oliver Raterink",
  "Antonio Romano",
  "Alessandro Russo",
  "Ivan Stoyanov Sulev",
  "Harry Winks",
  "Gennaro Borrelli",
  "Sebastiano Esposito",
  "Zito Luvumbo",
  "Parfait Mendy",
  "Kingstone Mutandwa",
  "Yassin Trepy",
  "Nikita Contini",
  "Alex Meret",
  "Vanja Milinković-Savić",
  "Diego Spinelli",
  "Sam Beukema",
  "Alessandro Buongiorno",
  "Giovanni Di Lorenzo",
  "Carmine Garofalo",
  "Miguel Gutiérrez",
  "Luca Marianucci",
  "Pasquale Mazzocchi",
  "Mathías Olivera",
  "Amir Rrahmani",
  "Leonardo Spinazzola",
  "André-Frank Zambo Anguissa",
  "Kevin De Bruyne",
  "Emanuele De Chiara",
  "Michael Folorunsho",
  "Billy Gilmour",
  "Stanislav Lobotka",
  "Scott McTominay",
  "Vincenzo Prisco",
  "Antonio Vergara",
  "Alisson Santos",
  "Giuseppe Ambrosino",
  "Walid Cheddira",
  "Giovane",
  "Rasmus Højlund",
  "Noa Lang",
  "Lorenzo Lucca",
  "Romelu Lukaku",
  "Matteo Politano",
  "Alessio Zerbin",
  "Maduka Okoye",
  "Daniele Padelli",
  "Nicolò Bertola",
  "Saba Goglichidze",
  "Christian Kabasele",
  "Hassane Kamara",
  "Thomas Kristensen",
  "Oumar Solet",
  "Omar Traoré",
  "Alessandro Zanoli",
  "Jordan Zemura",
  "Jhon Arizala",
  "Aliou Camara",
  "Giorgi Chakvetadze",
  "Jurgen Ekkelenkamp",
  "Unai Gómez",
  "Jesper Karlström",
  "Sandi Lovrić",
  "Liam Miller",
  "Branimir Mlačić",
  "Rui Modesto",
  "Jakub Piotrowski",
  "Nicolò Zaniolo",
  "Oier Zarraga",
  "Vakoun Bayo",
  "Aleksander Buksa",
  "Keinan Davis",
  "Idrissa Gueye",
  "Gabriele Vinciati",
  "Justin Bijlow",
  "Egor Lysionok",
  "Mamedi Doucoure",
  "Kris Gecaj",
  "Klisys",
  "Alen Kumer Celik",
  "Alessandro Marcandalli",
  "Aarón Martín",
  "Brooke Norton-Cuffy",
  "Leo Østigård",
  "Saba Otoa",
  "William L. Ouedraogo",
  "David Puczka",
  "Stefano Sabelli",
  "Johan Vásquez",
  "Matías Vaz",
  "Alexsandro Amorim",
  "Filippo Carbone",
  "Hugo Cuenca",
  "Mikael Ellertsson",
  "Morten Frendrup",
  "Jacopo Grossi",
  "Gaël Lafont",
  "Pietro Masini",
  "Evan Meichtry",
  "Lorenzo Colombo",
  "Elias Havel",
  "Joi Nuredini",
  "Marco Romano",
  "Elia Spicuglia",
  "Leonardo Venturino",
  "Vítinha",
  "Samuel Wiafe",
  "Michele Di Gregorio",
  "Riccardo Huli",
  "Mattia Perin",
  "Carlo Pinsoglio",
  "Andrei Radu",
  "Simone Scaglia",
  "Gleison Bremer",
  "Juan Cabal",
  "Andrea Cambiaso",
  "Zeki Çelik",
  "Federico Gatti",
  "Javier Gil",
  "João Mário",
  "Pierre Kalulu",
  "Lloyd Kelly",
  "Nicholas Rizzo",
  "Jonas Rouhi",
  "Vasilije Adžić",
  "Teun Koopmeiners",
  "Manuel Locatelli",
  "Weston McKennie",
  "Fabio Miretti",
  "Khéphren Thuram",
  "Jérémie Boga",
  "Francisco Conceição",
  "Jonathan David",
  "Jeff Ekhator",
  "Arkadiusz Milik",
  "Loïs Openda",
  "Kenan Yıldız",
  "Edon Zhegrova",
  "Giacomo De Marzi",
  "Pierluigi Gollini",
  "Mile Svilar",
  "Devis Vásquez",
  "Radoslaw Żelezny",
  "Angeliño",
  "Daniele Ghilardi",
  "Mario Hermoso",
  "Edoardo Lulli",
  "Gianluca Mancini",
  "Jacopo Mirra",
  "Evan Ndicka",
  "Devyne Rensch",
  "Moustapha Seck",
  "Wesley",
  "Jan Ziółkowski",
  "Bryan Cristante",
  "Mattia Della Rocca",
  "Neil El Aynaoui",
  "Manu Koné",
  "Niccolò Pisilli",
  "Alessandro Arena",
  "Artem Dovbyk",
  "Paulo Dybala",
  "Donyell Malen",
  "Matías Soulé",
  "Ricardo Vaz",
  "Marco Carnesecchi",
  "Piotr Pardel",
  "Francesco Rossi",
  "Marco Sportiello",
  "Hemsley Ahanor",
  "Mitchel Bakker",
  "Berat Djimsiti",
  "Isak Hien",
  "Sead Kolašinac",
  "Odilon Kossounou",
  "Relja Obrić",
  "Giorgio Scalvini",
  "Davide Zappacosta",
  "Raoul Bellanova",
  "Lorenzo Bernasconi",
  "Charles De Ketelaere",
  "Éderson",
  "Gianluca Gaetano",
  "Sergej Levak",
  "Daniel Maldini",
  "Mario Pašalić",
  "Lazar Samardžić",
  "Ibrahim Sulemana",
  "Nicola Zalewski",
  "Marten de Roon",
  "Federico Cassa",
  "Nikola Krstović",
  "Giacomo Raspadori",
  "Gianluca Scamacca",
  "Kamaldeen Sulemana",
  "Dominic Vavassori",
  "Matteo Franceschelli",
  "Riccardo Gnudi",
  "Matteo Pessina",
  "Federico Ravaglia",
  "Łukasz Skorupski",
  "Davide Baroncioni",
  "Nicolò Casale",
  "Emil Helland",
  "Jhon Lucumí",
  "Torbjørn Heggem",
  "Juan Miranda",
  "Martin Vitík",
  "Lewis Ferguson",
  "Emil Holm",
  "Nikola Moro",
  "Tommaso Pobega",
  "Nadir Zortea",
  "Federico Bernardeschi",
  "Lorenzo Caccavo",
  "Nicolò Cambiaghi",
  "Francesco Castaldo",
  "Santiago Castro",
  "Thijs Dallinga",
  "Benjamín Domínguez",
  "Jens Odgaard",
  "Riccardo Orsolini",
  "Jonathan Rowe",
  "Oliver Christensen",
  "Luca Lezzerini",
  "Mattia Magalotti",
  "David de Gea",
  "Lorenzo Balbo",
  "Pietro Comuzzo",
  "Dodô",
  "Radu Drăgușin",
  "Niccolò Fortini",
  "Álex Jiménez",
  "Eman Košpo",
  "Fabiano Parisi",
  "Marin Pongračić",
  "Luca Ranieri",
  "Edoardo Sadotti",
  "Viery",
  "Arthur Atta",
  "Pietro Bonanno",
  "Marco Brescianini",
  "Lorenzo Deli",
  "Giovanni Fabbian",
  "Nicolò Fagioli",
  "Robin Gosens",
  "Rolando Mandragora",
  "Cher Ndour",
  "Pirro",
  "Simon Sohm",
  "Giacomo Bertolini",
  "Riccardo Braschi",
  "Albert Guðmundsson",
  "Moise Kean",
  "M'Bala Nzola",
  "Roberto Piccoli",
  "Giacomo Puzzoli",
  "Franco Israel",
  "Alberto Paleari",
  "Luca Siviero",
  "Cristiano Biraghi",
  "Saúl Coco",
  "Ali Dembélé",
  "Ardian Ismajli",
  "Marcus Pedersen",
  "Matteo Pellini",
  "William Acquah",
  "Faustino Anjorin",
  "Cesare Casadei",
  "Gvidas Gineitis",
  "Ivan Ilić",
  "Emirhan İlkhan",
  "Gaetano Oristanio",
  "Nikola Vlašić",
  "Zakaria Aboukhlal",
  "Ché Adams",
  "Tommaso Gabellini",
  "Sandro Kulenović",
  "Alieu Njie",
  "Giovanni Simeone",
  "Duván Zapata",
  "Nicola Leali",
  "Lorenzo Montipò",
  "Giacomo Toniolo",
  "Reda Belghali",
  "Domagoj Bradarić",
  "Davide De Battisti",
  "Andrias Edmundsson",
  "Martin Frese",
  "Seid Korač",
  "Daniel Oyegoke",
  "Tobias Slotsager",
  "Lorenzo Bega",
  "Antoine Bernede",
  "Fallou Cham",
  "Abdou Harroui",
  "Cheikh Niasse",
  "Julian Peci",
  "Suat Serdar",
  "Tomáš Suslov",
  "Lukas Szimionas",
  "Kion Bowie",
  "Stefano Cerbone",
  "Isaac",
  "Grigoris Kastanos",
  "Lorenzo Monticelli",
  "Daniel Mosquera",
  "Amin Sarr",
  "Ioan Vermeșan",
  "Alessandro Calligaris",
  "Raffaele Di Gennaro",
  "Josep Martínez",
  "Ivan Provedel",
  "Alessio Taho",
  "Manuel Akanji",
  "Alessandro Bastoni",
  "Yann Bisseck",
  "Matteo Cocchi",
  "Federico Dimarco",
  "Yassine Maye",
  "Ebenezer Akinsanmiro",
  "Nicolò Barella",
  "Thomas Berenbruch",
  "Lorenzo Bovo",
  "Hakan Çalhanoğlu",
  "Carlos Augusto",
  "Amadou Diouf",
  "Davide Frattesi",
  "Issiaka Kamate",
  "Henrikh Mkhitaryan",
  "Aleksandar Stanković",
  "Petar Sučić",
  "Luka Topalović",
  "Piotr Zieliński",
  "Ange-Yoan Bonny",
  "Francesco Esposito",
  "Matteo Lavelli",
  "Luis Henrique",
  "Lautaro Martínez",
  "Mattia Mosconi",
  "Matteo Spinaccè",
  "Marcus Thuram",
  "Samuele Perisan",
  "Mattia Curto",
  "Gabriele Guarino",
  "Gabriele Indragoli",
  "Matteo Lovato",
  "Luca Tosto",
  "Luca Belardinelli",
  "Jesper Ceesay",
  "Duccio Degli Innocenti",
  "Lorenzo Ignacchiti",
  "Luca Magnino",
  "Edoardo Saporiti",
  "Gerard Yepes",
  "Flavio Bianchi",
  "Salvatore Elia",
  "Boris Popov",
  "Stiven Shpendi",
  "Matteo Grandi",
  "Alessandro Pozzi",
  "Filip Stanković",
  "Armel Bella-Kotchap",
  "Angel Gomes",
  "Ridgeciano Haps",
  "Thierry Correia",
  "Romaric Sagrado",
  "Joël Schingtienne",
  "Aly Sidibé",
  "Marin Šverko",
  "Toma Bašić",
  "Leonardo Berardi",
  "Bjarki Bjarkason",
  "Emil Bohinen",
  "Gianluca Busio",
  "Matteo Dagasso",
  "Alfred Duncan",
  "Lamine Dabo",
  "Bartol Franjić",
  "Antoine Hainaut",
  "Þórir Helgason",
  "Nunzio Lella",
  "Akinsanmiro Okoro",
  "Kike Pérez",
  "Michael Venturi",
  "John Yeboah",
  "Andrea Adorante",
  "Antonio Casas",
  "Mattia Compagnon",
  "Mateo Farji",
  "Daniel Fila",
  "Lion Lauberbach",
  "Kacper Lisman",
  "Albion Rrahmani",
  "Gabriele Astaldi",
  "Gabriele Casentini",
  "Edoardo Corvi",
  "Giovanni Daffara",
  "Alessandro Mazzocchi",
  "Filippo Rinaldi",
  "Zion Suzuki",
  "Samuel Britschgi",
  "Franco Carboni",
  "Alessandro Circati",
  "Bernardo Conde",
  "Enrico Del Prato",
  "Dominik Drobnic",
  "Amath N'Diaye",
  "Matteo Troilo",
  "Lautaro Valenti",
  "Emanuele Valeri",
  "Pontus Almqvist",
  "Adrián Bernabé",
  "Benjamin Cremaschi",
  "Mandela Keita",
  "Hans Nicolussi Caviglia",
  "Jacob Ondrejka",
  "Carlos Ordoñez",
  "Edoardo Plicco",
  "Oliver Sørensen",
  "Edoardo Tigani",
  "Adrian Benedyczak",
  "Alessandro Cardinali",
  "Nathan Elphege",
  "Daniel Mikołajewski",
  "Mateo Pellegrino",
  "Daniele Bleve",
  "Wladimiro Falcone",
  "Christian Früchtl",
  "Jasper Samooja",
  "Seko Fofana",
  "Antonino Gallo",
  "Kialonda Gaspar",
  "Gaby Jean",
  "Owen Kouassi",
  "Corrie Ndaba",
  "Matías Pérez",
  "Jamil Siebert",
  "Tiago Gabriel",
  "Danilo Veiga",
  "Lassana Coulibaly",
  "Omri Gandelman",
  "Olaf Gorter",
  "Mohamed Kaba",
  "Niko Kovač",
  "Youssef Maleh",
  "Filip Marchwiński",
  "Ousmane Ngom",
  "Álex Sala",
  "Lameck Banda",
  "Santiago Pierotti",
  "Nikola Štulić",
  "Jean Butez",
  "Noel Törnqvist",
  "Andrés Cuenca",
  "Alberto Dossena",
  "Edoardo Goldaniga",
  "Kaiki",
  "Marc-Oliver Kempf",
  "Stefan Posch",
  "Jacobo Ramón Naveros",
  "Ivan Smolčić",
  "Álex Valle",
  "Ignace Van der Brempt",
  "Mërgim Vojvoda",
  "Martin Baturina",
  "Levente Bősze",
  "Maxence Caqueret",
  "Riccardo Cassano",
  "Lucas da Cunha",
  "Amane Lahdo",
  "Arthur Le Borgne",
  "Luis Milla",
  "Nico Paz",
  "Máximo Perrone",
  "Jesús Rodríguez",
  "Jayden Addai",
  "Assane Diao",
  "Anastasios Douvikas",
  "Alieu Fadera",
  "Nicolas Kühn",
  "Álvaro Morata",
  "Stefano Pisati",
  "Samuele Pizzignacco",
  "Aljaž Strajnar",
  "Demba Thiam",
  "Andrea Vailati",
  "Valentin Antov",
  "Adam Bakoune",
  "Samuele Birindelli",
  "Arvid Brorsson",
  "Andrea Carboni",
  "Filippo Delli Carri",
  "Emmanuel Kouadio",
  "Lorenzo Lucchesi",
  "Luca Ravanelli",
  "Andrea Colpani",
  "Pedro Obiang",
  "Fabrice Ondoa",
  "Filippo Reita",
  "Keita Baldé",
  "Patrick Ciurria",
  "Patrick Cutrone",
  "Omari Forson",
  "Dany Mota",
  "Milan Mout",
  "Andrea Petagna"
];

async function main() {
  const fallos: { nombre: string; motivo: string }[] = [];
  const renombrados: { buscado: string; encontrado: string }[] = [];
  let exitos = 0;

  for (const entrada of JUGADORES_INICIALES) {
    const nombre = typeof entrada === "string" ? entrada : entrada.nombre;
    const urlManual = typeof entrada === "string" ? undefined : entrada.url;

    console.log(`\n→ Sincronizando ${nombre}${urlManual ? " (vía URL manual)" : ""}...`);
    const resultado = await syncJugadorDesdeWikipedia(prisma, nombre, urlManual);

    if (resultado.ok) {
      exitos++;
      if (resultado.renombrado) {
        renombrados.push({ buscado: nombre, encontrado: resultado.nombreUsado });
      }
      const aviso = resultado.renombrado
        ? `  (encontrado como "${resultado.nombreUsado}", revisa que sea correcto)`
        : "";
      console.log(
        `  ✓ ${resultado.etapas} etapas guardadas (${resultado.goles} goles, ${resultado.partidos} partidos totales)${aviso}`
      );
    } else {
      fallos.push({ nombre, motivo: resultado.motivo });
      console.warn(`  ✗ Fallo: ${resultado.motivo}`);
    }

    await new Promise((r) => setTimeout(r, 1200));
  }

  await prisma.$disconnect();

  console.log(`\n=== Resumen ===`);
  console.log(`Sincronizados con éxito: ${exitos}`);
  console.log(`Fallos: ${fallos.length}`);
  console.log(`Renombrados (revisar): ${renombrados.length}`);

  // Guardamos fallos y renombrados en ficheros de texto, para no perderlos
  // en el scroll del terminal y poder revisarlos con calma.
  const lineasFallos = fallos.map((f) => `${f.nombre} — ${f.motivo}`).join("\n");
  await writeFile("scripts/sync-fallos.txt", lineasFallos, "utf-8");

  const lineasRenombrados = renombrados
    .map((r) => `${r.buscado} -> ${r.encontrado}`)
    .join("\n");
  await writeFile("scripts/sync-renombrados.txt", lineasRenombrados, "utf-8");

  console.log(`\nGuardado: scripts/sync-fallos.txt y scripts/sync-renombrados.txt`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});