// scripts/syncPlayers.ts
//
// Sincroniza una lista de jugadores concreta, escrita a mano.
// Ejecutar con: npx tsx scripts/syncPlayers.ts
 
import "dotenv/config";
import { writeFile } from "node:fs/promises";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { syncJugadorDesdeWikipedia } from "../src/lib/wikipediaSync";
 
const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

const JUGADORES_INICIALES = [
  "Altay Bayındır",
  "Karl Darlow",
  "Senne Lammens",
  "Diogo Dalot",
  "Patrick Dorgu",
  "Tyler Fredricson",
  "Ayden Heaven",
  "Godwill Kukonki",
  "Harry Maguire",
  "Lisandro Martínez",
  "Noussair Mazraoui",
  "Luke Shaw",
  "Leny Yoro",
  "Andrey Santos",
  "Bruno Fernandes",
  "Jack Fletcher",
  "Tyler Fletcher",
  "Kobbie Mainoo",
  "Jack Moorhouse",
  "Mason Mount",
  "Youri Tielemans",
  "Manuel Ugarte",
  "Matheus Cunha",
  "Amad Diallo",
  "Shea Lacey",
  "Bryan Mbeumo",
  "Benjamin Šeško",
  "Joshua Zirkzee",
  "Aidan Harris",
  "Evan Jaouen",
  "Nick Pope",
  "Aaron Ramsdale",
  "Max Thompson",
  "Sven Botman",
  "Dan Burn",
  "Lewis Hall",
  "Tino Livramento",
  "Alex Murphy",
  "Leo Shahar",
  "Malick Thiaw",
  "Bruno Guimarães",
  "Joelinton",
  "Lewis Miley",
  "Jacob Murphy",
  "Sean Neave",
  "Park Seung-Soo",
  "Jacob Ramsey",
  "Sean Steur",
  "El Bilal Touré",
  "Joe Willock",
  "Harvey Barnes",
  "Anthony Elanga",
  "William Osula",
  "Yoane Wissa",
  "Nick Woltemade",
  "Fraser Forster",
  "Đorđe Petrović",
  "Bafodé Diakité",
  "James Hill",
  "Veljko Milosavljević",
  "Adam Smith",
  "Adrien Truffert",
  "Tyler Adams",
  "Amine Adli",
  "Ryan Christie",
  "Lewis Cook",
  "Malcom Dacosta",
  "Alex Scott",
  "Connor Stevens",
  "Marcus Tavernier",
  "Balázs Tóth",
  "David Brooks",
  "Evanilson",
  "Ben Doak",
  "Justin Kluivert",
  "Eli Junior Kroupi",
  "Rayan",
  "Remy Rees-Dottin",
  "Álvaro Rodríguez",
  "Enes Ünal",
  "Benjamin Lecomte",
  "Bernd Leno",
  "Samuel Amissah",
  "Joachim Andersen",
  "Calvin Bassey",
  "Timothy Castagne",
  "Jorge Cuenca",
  "Issa Diop",
  "Antonee Robinson",
  "Kenny Tete",
  "Sander Berge",
  "Oscar Bobb",
  "Tom Cairney",
  "Alex Iwobi",
  "Joshua King",
  "Saša Lukić",
  "Harrison Reed",
  "Ryan Sessegnon",
  "Emile Smith Rowe",
  "Kevin",
  "Jonah Kusi-Asare",
  "Rodrigo Muniz",
  "Daniel Bentley",
  "Jake Gracey",
  "Sam Johnstone",
  "José Sá",
  "Hugo Bueno",
  "Santiago Bueno",
  "Rodrigo Gomes",
  "Ladislav Krejčí",
  "Saheed Olagunju",
  "Pedro Lima",
  "Toti Gomes",
  "Kieran Trippier",
  "David Møller Wolfe",
  "André",
  "Jean-Ricner Bellegarde",
  "Tyrese Edozie",
  "João Gomes",
  "Fer López",
  "Yerson Mosquera",
  "Leon Rawlings",
  "Adam Armstrong",
  "Tolu Arokodare",
  "Hwang Hee-Chan",
  "Raúl Jiménez",
  "Maksim Mane",
  "Rafik Saïd",
  "Ethan Sutherland",
  "Jackson Tchatchoua",
  "Alisson Becker",
  "Giorgi Mamardashvili",
  "Kornel Miściur",
  "Ármin Pécsi",
  "Freddie Woodman",
  "Joe Gomez",
  "Jérémy Jacquet",
  "Milos Kerkez",
  "Tarik Ndiaye",
  "Calvin Ramsay",
  "Virgil van Dijk",
  "Wataru Endo",
  "Jeremie Frimpong",
  "Ryan Gravenberch",
  "Curtis Jones",
  "Alexis Mac Allister",
  "James McConnell",
  "Kieran Morrison",
  "Amara Nallo",
  "Trey Nyoni",
  "Dominik Szoboszlai",
  "Florian Wirtz",
  "Federico Chiesa",
  "Hugo Ekitike",
  "Cody Gakpo",
  "Alexander Isak",
  "Víctor Muñoz",
  "Rio Ngumoha",
  "William Wright",
  "George Long",
  "Daniel Peretz",
  "James Bree",
  "Tyler Dobson-Ventura",
  "Taylor Harwood-Bellis",
  "Ryan Manning",
  "Jayden Quarshie",
  "Jack Stephens",
  "Welington",
  "Nathan Wood-Gordon",
  "Finn Azaz",
  "Cameron Bragg",
  "Shea Charles",
  "Flynn Downes",
  "Tom Fellows",
  "Caspar Jander",
  "Kuryu Matsuki",
  "Joe O'Brien-Whitmarsh",
  "Moses Sesay",
  "Brandon Williams",
  "Cameron Archer",
  "Samuel Edozie",
  "Cyle Larin",
  "Nicholas Oyekunle",
  "Jay Robinson",
  "Léo Scienza",
  "Kepa Arrizabalaga",
  "Illan Meslier",
  "Jack Porter",
  "Kian Ranson",
  "David Raya",
  "Tommy Setford",
  "Riccardo Calafiori",
  "Jaden Dixon",
  "Gabriel Magalhães",
  "Piero Hincapié",
  "Myles Lewis-Skelly",
  "Cristhian Mosquera",
  "William Saliba",
  "Maldini Salmon",
  "Jurrien Timber",
  "Ben White",
  "Max Dowman",
  "Eberechi Eze",
  "Ismeal Ibrahim",
  "Mikel Merino",
  "Christian Nørgaard",
  "Ethan Nwaneri",
  "Martin Ødegaard",
  "Declan Rice",
  "Martín Zubimendi",
  "Bailey-Joseph",
  "Gabriel Jesus",
  "Viktor Gyökeres",
  "Andre Annous",
  "Kai Havertz",
  "Noni Madueke",
  "Gabriel Martinelli",
  "Bukayo Saka",
  "Tom King",
  "Jordan Pickford",
  "Mark Travers",
  "Adam Aznou Ben Cheikh",
  "Jarrad Branthwaite",
  "Elijah Xavier Campbell",
  "Vitaliy Mykolenko",
  "Jake O'Brien",
  "Nathan Patterson",
  "James Tarkowski",
  "Reece Welch",
  "Carlos Alcaraz",
  "Harrison Armstrong",
  "Kiernan Dewsbury-Hall",
  "James Garner",
  "Hayden Hackney",
  "Tim Iroegbunam",
  "Dwight McNeil",
  "Max Röhl",
  "Louie Barry",
  "Beto",
  "Tyler Dibling",
  "Tyrique George",
  "Iliman Ndiaye",
  "Asmir Begović",
  "Harry French",
  "Jakub Stolarczyk",
  "Fran Vieites",
  "Olayinka Aluko",
  "Waly Coulibaly",
  "Wout Faes",
  "Archie Gray",
  "Victor Kristiansen",
  "Ben Nelson",
  "Caleb Okoli",
  "Lewis Page",
  "Harry Souttar",
  "Luke Thomas",
  "Thomas Wilson-Brown",
  "Will Alves",
  "Sammy Braybrooke",
  "Hamza Choudhury",
  "Bobby De Cordova-Reid",
  "Oliver Skipp",
  "Jonny Evans",
  "Abdul Fatawu",
  "Stephy Mavididi",
  "Silko Amari Otieno Thomas",
  "Brandon Austin",
  "Martin Dúbravka",
  "Antonín Kinský",
  "Guglielmo Vicario",
  "James Byfield",
  "Kevin Danso",
  "Ben Davies",
  "Archie Gray",
  "Max Hardy",
  "Pedro Porro",
  "Andrew Robertson",
  "Cristian Romero",
  "James Rowswell",
  "Marcos Senesi",
  "Souza",
  "Djed Spence",
  "Destiny Udogie",
  "Jan Paul van Hecke",
  "Micky van de Ven",
  "Rodrigo Bentancur",
  "Lucas Bergvall",
  "Mateus Fernandes",
  "Conor Gallagher",
  "Tyrese Hall",
  "Rio Kyerematen",
  "James Maddison",
  "Callum Olusesi",
  "Pape Matar Sarr",
  "Xavier Simons",
  "Sandro Tonali",
  "Wilson Odobert",
  "Richarlison",
  "Dane Scarlett",
  "Dominic Solanke",
  "Mathys Tel",
  "Tom Thompson",
  "Luca Williams-Barnett",
  "Alphonse Areola",
  "Mads Hermansen",
  "Fin Herrick",
  "El Hadji Diouf",
  "Airidas Golambeckis",
  "Max Kilman",
  "Konstantinos Mavropanos",
  "Ezra Mayers",
  "Oliver Scarles",
  "Jean-Clair Todibo",
  "Kyle Walker-Peters",
  "Aaron Wan-Bissaka",
  "N'Golo Kanté",
  "Kian Lamadrid",
  "Soungoutou Magassa",
  "Lewis Orford",
  "Freddie Potts",
  "Tomáš Souček",
  "James Ward-Prowse",
  "Josh Ajala",
  "Jarrod Bowen",
  "Valentín Castellanos",
  "Pablo Fornals",
  "Crysencio Summerville",
  "Filip Jörgensen",
  "Max Merrick",
  "Robert Sánchez",
  "Teddy Sharman-Lowe",
  "Gabriel Słonina",
  "Joshua Kofi Acheampong",
  "Tosin Adarabioyo",
  "Denner",
  "Benoît Badiashile",
  "Trevoh Chalobah",
  "Levi Colwill",
  "Wesley Fofana",
  "Malo Gusto",
  "Jorrel Hato",
  "Reece James",
  "Matia Palestra",
  "Malang Sarr",
  "Moisés Caicedo",
  "Michael Eboue",
  "Landon Emenalo",
  "Dário Essugo",
  "Enzo Fernández",
  "Charlie Holland",
  "Reiss Kavuma McQueen",
  "Roméo Lavia",
  "Cole Palmer",
  "Ronnie Walsh",
  "Liam Delap",
  "Emanuel Emegha",
  "Estêvão",
  "Alejandro Garnacho",
  "Jamie Bynoe-Gittens",
  "Marc Guiu",
  "João Pedro",
  "Shumaira Mheuka",
  "Pedro Neto",
  "Geovany Tcherno Quenda",
  "Marcus Bettinelli",
  "Gianluigi Donnarumma",
  "James Trafford",
  "Rayan Aït-Nouri",
  "Max Alleyne",
  "Rúben Dias",
  "Marc Guéhi",
  "Joško Gvardiol",
  "Abdukodir Khusanov",
  "Rico Lewis",
  "Stephen Mfuni",
  "Elliot Anderson",
  "Rayan Cherki",
  "Phil Foden",
  "Charlie Gray",
  "Mateo Kovačić",
  "Ryan McAidoo",
  "Nico González",
  "Matheus Nunes",
  "Nico O'Reilly",
  "Tijjani Reijnders",
  "Rodri",
  "Tarik Samba",
  "Jérémy Doku",
  "Erling Haaland",
  "Omar Marmoush",
  "Joel Monga",
  "Divine Mukasa",
  "Sávio",
  "Antoine Semenyo",
  "Jason Steele",
  "Bart Verbruggen",
  "Olivier Boscagli",
  "Costinha",
  "Maxim De Cuyper",
  "Igor Julio",
  "Ferdi Kadıoğlu",
  "Pascal Struijk",
  "Milan Svoboda",
  "Luka Vušković",
  "Yasin Ayari",
  "Carlos Baleba",
  "Diego Gómez",
  "Pascal Groß",
  "Jack Hinshelwood",
  "Harry Howell",
  "Matt O'Riley",
  "Mats Wieffer",
  "Charalampos Kostoulas",
  "Yankuba Minteh",
  "Kaoru Mitoma",
  "Rodrigo Miguel Ferreira Rêgo",
  "Georginio Rutter",
  "Danny Welbeck",
  "Zane Yohanna",
  "Walter Benítez",
  "Dean Henderson",
  "Remi Matthews",
  "Josias Canvot",
  "Rio Cardines",
  "Nathaniel Clyne",
  "Daniel Edward Peter Imray",
  "Maxence Lacroix",
  "Óscar Mingueza",
  "Tyrick Mitchell",
  "Daniel Muñoz",
  "Chadi Riad",
  "Chris Richards",
  "Borna Sosa",
  "Justin Devenny",
  "Will Hughes",
  "Daichi Kamada",
  "Jefferson Lerma",
  "Adam Wharton",
  "Brennan Johnson",
  "Jørgen Strand Larsen",
  "Zach Marsh",
  "Jean-Philippe Mateta",
  "Yeremy Pino",
  "Ismaïla Sarr",
  "Ellery Balcombe",
  "Caoimhín Kelleher",
  "Hákon Valdimarsson",
  "Kristoffer Ajer",
  "Nathan Collins",
  "Rico Henry",
  "Aaron Hickey",
  "Michael Kayode",
  "Ethan Pinnock",
  "Jason Stephenson",
  "Sepp van den Berg",
  "Luka Bentt",
  "Mikkel Damsgaard",
  "Josh Dasilva",
  "Jordan Henderson",
  "Vitaly Janelt",
  "Mathias Jensen",
  "Keane Lewis-Potter",
  "Riley Owen",
  "Kevin Schade",
  "Jannik Schuster",
  "Yehor Yarmolyuk",
  "Jaidon Anthony",
  "Kaye Iyowuna Furo",
  "Dango Ouattara",
  "Ollie Shield",
  "Thiago Alcântara",
  "Callum Wilson",
  "David Button",
  "Alex Palmer",
  "Christian Walton",
  "Elkan Baggott",
  "Sonny Boniface",
  "Leif Davis",
  "Darnell Furlong",
  "Jacob Greaves",
  "Cédric Kipré",
  "Dara O'Shea",
  "Wes Burns",
  "Azor Matusiwa",
  "Marcelino Núñez",
  "Sammie Szmodics",
  "Jack Taylor",
  "Chuba Akpom",
  "Jack Clarke",
  "Sindre Egeli",
  "Emersonn",
  "George Hirst",
  "Kasey McAteer",
  "Anis Mehmeti",
  "Jaden Philogene",
  "John",
  "Matz Sels",
  "Keehan Willows",
  "Zach Abbott",
  "Ola Aina",
  "Jair",
  "Benjamin Hammond",
  "Justin Thomas Hanks",
  "Nikola Milenković",
  "Morato",
  "Murillo",
  "Luca Netz",
  "Nicolò Savona",
  "Jack Sinclair",
  "Jack Ethan Thompson",
  "Neco Williams",
  "Nicolás Domínguez",
  "Morgan Gibbs-White",
  "Callum Hudson-Odoi",
  "James McAtee",
  "Ibrahim Sangaré",
  "Archie Whitehall",
  "Ryan Yates",
  "Eric Emanuel da Silva Moreira",
  "Taiwo Awoniyi",
  "Dilane Bakwa",
  "Zach Blake",
  "Omari Hutchinson",
  "Igor Jesus",
  "Dan Ndoye",
  "Lamine Sillah",
  "Chris Wood",
  "Marco Bizot",
  "Emiliano Martínez",
  "Sam Proctor",
  "James Wright",
  "Lamare Bogarde",
  "Matty Cash",
  "Moustapha Cissé",
  "Lucas Digne",
  "Andrés García",
  "Ezri Konsa",
  "Victor Lindelöf",
  "Ian Maatsen",
  "Tyrone Mings",
  "Pau Torres",
  "Ross Barkley",
  "Emiliano Buendía",
  "Ben Burrows",
  "Tom Carroll",
  "George Hemmings",
  "Jamaldeen Jimoh",
  "Manu Koné",
  "John McGinn",
  "Amadou Onana",
  "Morgan Rogers",
  "Tammy Abraham",
  "Alysson Edward",
  "Leon Bailey",
  "Evann Guessand",
  "Brian Madjo",
  "Travis Mulley",
  "Ollie Watkins"
]

 
async function main() {
  const fallos: { nombre: string; motivo: string }[] = [];
  const renombrados: { buscado: string; encontrado: string }[] = [];
  let exitos = 0;
 
  for (const nombre of JUGADORES_INICIALES) {
    console.log(`\n→ Sincronizando ${nombre}...`);
    const resultado = await syncJugadorDesdeWikipedia(prisma, nombre);
 
    if (resultado.ok) {
      exitos++;
      if (resultado.renombrado) {
        renombrados.push({ buscado: nombre, encontrado: resultado.nombreUsado });
      }
      const aviso = resultado.renombrado
        ? `  (encontrado como "${resultado.nombreUsado}", revisa que sea correcto)`
        : "";
      console.log(
        `  ✓ ${resultado.etapas} etapas guardadas (${resultado.goles} goles, ${resultado.partidos} partidos totales)${aviso}`
      );
    } else {
      fallos.push({ nombre, motivo: resultado.motivo });
      console.warn(`  ✗ Fallo: ${resultado.motivo}`);
    }
 
    await new Promise((r) => setTimeout(r, 1200));
  }
 
  await prisma.$disconnect();
 
  console.log(`\n=== Resumen ===`);
  console.log(`Sincronizados con éxito: ${exitos}`);
  console.log(`Fallos: ${fallos.length}`);
  console.log(`Renombrados (revisar): ${renombrados.length}`);
 
  // Guardamos fallos y renombrados en ficheros de texto, para no perderlos
  // en el scroll del terminal y poder revisarlos con calma.
  const lineasFallos = fallos.map((f) => `${f.nombre} — ${f.motivo}`).join("\n");
  await writeFile("scripts/sync-fallos.txt", lineasFallos, "utf-8");
 
  const lineasRenombrados = renombrados
    .map((r) => `${r.buscado} -> ${r.encontrado}`)
    .join("\n");
  await writeFile("scripts/sync-renombrados.txt", lineasRenombrados, "utf-8");
 
  console.log(`\nGuardado: scripts/sync-fallos.txt y scripts/sync-renombrados.txt`);
}
 
main().catch((e) => {
  console.error(e);
  process.exit(1);
});